#+TITLE: Tansen Dragonfistface
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+OPTIONS: num:nil

#+NAME: BASIC
| Race       | Class | Level | Background | Alignment   | Experince Points |
|------------+-------+-------+------------+-------------+------------------|
| Dragonborn | Monk  |    13 | City Watch | Lawful Good |                  |

** Attributes and Skills

#+NAME: ATTRIBUTES
| Attribute | Value | Mod | Save? | Skills          | Proficient? |
|-----------+-------+-----+-------+-----------------+-------------|
| STR       |    18 |   4 | [X]   | Athletics       | [X]         |
|           |       |     |       |                 |             |
|-----------+-------+-----+-------+-----------------+-------------|
| DEX       |    20 |   5 | [X]   | Acrobatics      |             |
|           |       |     |       | Stealth         | [X]         |
|-----------+-------+-----+-------+-----------------+-------------|
| CON       |    16 |   3 |       |                 |             |
|-----------+-------+-----+-------+-----------------+-------------|
| INT       |    11 |   0 |       | Arcana          |             |
|           |       |     |       | History         | [X]         |
|           |       |     |       | Investigation   |             |
|           |       |     |       | Nature          |             |
|           |       |     |       | Religion        |             |
|-----------+-------+-----+-------+-----------------+-------------|
| WIS       |    19 |   4 |       | Animal handling |             |
|           |       |     |       | Insight         | [X]         |
|           |       |     |       | Medicine        |             |
|           |       |     |       | Perception      |             |
|           |       |     |       | Survival        |             |
|-----------+-------+-----+-------+-----------------+-------------|
| CHA       |    16 |   3 |       | Deception       |             |
|           |       |     |       | Intimidation    |             |
|           |       |     |       | Performance     |             |
|           |       |     |       | Persuasion      |             |
#+TBLFM: @2$3=(floor (($2-10)/2))::@4$3=(floor (($2-10)/2))::@6$3=(floor (($2-10)/2))::@7$3=(floor (($2-10)/2))::@12$3=(floor (($2-10)/2))::@17$3=(floor (($2-10)/2))

- +1 bonus to saving throws with [[Cloak of Protection][Cloak of Protection]].
- +3 bonus to saving throws with [[Ki Straps of the Grandmaster][Ki Straps]].

#+NAME: PASSIVE_ATTRIBUTES
| Passive Wisdom | Proficiency Bonus | Inspiration |
|----------------+-------------------+-------------|
|             14 |                 5 |           5 |
#+TBLFM: @2$1=(remote(ATTRIBUTES, @12$3) + 10)

** Combat Information
#+NAME: PASSIVE_COMBAT
| Initiative | Armor Class                   | Speed         | Current HP   | Temporary HP | Hit Dice  |
|------------+-------------------------------+---------------+--------------+--------------+-----------|
|          5 | 19 (Monk unarmored AC)        | Base: 30      | Max: 105     |              | Max: 13d8 |
|            | +1 (with [[Cloak of Protection][Cloak of Protection]]) | Unarmored: 50 | Current: 105 |              | Used:     |
|            | +1 (in Barovia)               |               |              |              |           |
#+TBLFM: @2$1=(remote(ATTRIBUTES, @4$3))

*** Ki
#+NAME: KI
| Current Ki Points   | Ki Save DC |
|---------------------+------------|
| Max: 13             |         17 |
| +6 (with [[Ki Straps of the Grandmaster][Ki Straps]]) |            |
#+TBLFM: @2$2=(remote(ATTRIBUTES, @12$3) + remote(PASSIVE_ATTRIBUTES, @2$2) + 8)

*** Attacks and Spellcasting
#+NAME: BONUS
| Dex Mod | Proficiency Bonus |
|---------+-------------------|
|       5 |                 5 |
#+TBLFM: @2$1=(remote(ATTRIBUTES, @4$3))::@2$2=(remote(PASSIVE_ATTRIBUTES, @2$2))

#+NAME: ATTACKS
| Name            | Damage | Type  | Proficient | Range | Other Bonus                                            |
|-----------------+--------+-------+------------+-------+--------------------------------------------------------|
| Unarmed attack  |    1d8 | [[Elemental Combatant][Multi]] | [X]        |    60 | +3 to attack and damage rolls (with [[Ki Straps of the Grandmaster][Ki Straps]])         |
|                 |        |       |            |       | +1 to attack and damage rolls (with [[Insignia of Claws][Insignia of Claws]]) |
|                 |        |       |            |       | + half your monk level                                 |
|-----------------+--------+-------+------------+-------+--------------------------------------------------------|
| [[Detect Thoughts][Detect Thoughts]] |        |       |            |       |                                                        |

** Features and Proficiencies
#+NAME: RP
| Features and Traits | Proficiencies                                | Languages            |
|---------------------+----------------------------------------------+----------------------|
|                     | Artisan's tools, Shortswords, Simple weapons | All spoken languages |

** Equipment

*** Weapons and Armor

- <<Cloak of Protection>> Cloak of Protection ::
  Wondrous item, uncommon. Requires attunement. You gain a +1 bonus to AC and
  saving throws while you wear this cloak.
- <<Ki Straps of the Grandmaster>> Ki Straps of the Grandmaster ::
  Wondrous item, very rare. Requires attunement by a monk. When wrapped around
  both hands, these straps grant a +3 bonus to attack and damage rolls of your
  unarmed attacks and to the saving throw DCs of your Monk special abilities
  (like Stunning Strike, Martial Arts Techniques, Shadow and Elemental Spells
  and so on). In addition, you can regain 6 ki points as an action while wearing
  these straps. You can't use this property again until you finish a long rest.
- <<Insignia of Claws>> Insignia of Claws ::
  Wondrous item, uncommon. The jewels in the insignia of the Cult of the Dragon
  flare with purple light when you enter combat, empowering your natural fists
  or natural weapons. While wearing the insignia you gain a +1 bonus to the
  attack rolls and the damage rolls you make with unarmed strikes and natural
  weapons. Such attacks are considered to be magical.

*** Others

- Potion of Greater Healing (x1) ::
  Potion, Uncommon. You regain 4d4 + 4 hit points when you drink this
  potion. The potion's red liquid glimmers when agitated.
- Tower Ground Keys (#5, #6) ::
  Wondrous item, legendary. Platinum skeleton keys that open doors to different
  areas in and around the Tower of Shadows. These keys can be used anywhere and
  inserted into anything. Once turned, it take 1 minute for the door to form and
  open.

** <<Monastic Tradition>> Monastic Tradition

- Way of the Avatar ::
  (/Adapted from /u/Zetesofos's Way of the Four Elements/)

  You follow a monastic tradition that teaches you to harness the elements. When
  you focus your ki, you can align yourself with the forces of creation, and
  bend the four elements to your will, using them as an extension of your body.

  + Disciple of the Elements ::
    At 3rd level, you learn the [[Elemental Attunement][Elemental Attunement]], the [[Elemental Combatant][Elemental Combatant]],
    and the [[Elemental Shield][Elemental Shield]] disciplines. You learn two additional elemental
    disciplines of your choice at 6th level and again at 11th level, which are
    detailed in the [[Elemental Disciplines][Elemental Disciplines]] section below. Some disciplines
    require you to spend ki points when you use them, and some disciplines
    evolve as you get better at mastering the elements. Some disciplines allow
    you to cast certain spells, without requiring the material components.

    Whenever you learn a new elemental discipline, you can also replace one
    elemental discipline that you already know with a different discipline.

  + Adept of the Elements ::
    Beginning at 6th level, whenever you target one or more creatures with an
    elemental discipline, you can spend 1 ki point to force each creature to
    succeed on a Strength saving throw or be pushed 10 feet and be knocked
    prone.

  + Master of the Elements ::
    Starting at 11th level, when you use a cantrip granted by your
    [[Elemental Attunement][Elemental Attunement]] discipline, you can spend 1 ki point to increase their
    area of effect to a number of 5 foot cubes equal to your monk level.

  + Avatar of the Elements ::
    Once you reach 17th level, you are able to become a being of elemental might
    for a short period of time. As an action, you may cast one of the following
    spells: [[Investiture of Flame][Investiture of Flame]], [[Investiture of Ice][Investiture of Ice]], [[Investiture of Stone][Investiture of Stone]],
    [[Investiture of Wind][Investiture of Wind]].

    When you do so, you do not need to concentrate on the spell. If the spell
    requires a creature to make a saving throw, you use your Ki save DC. Once
    you use this feature, you cannot do so again until you complete a long rest.

  + <<Elemental Disciplines>> Elemental Disciplines ::
    - <<Elemental Attunement>> Elemental Attunement ::
      You can cast the following cantrips: [[Control Flames][Control Flames]], [[Gust][Gust]], [[Mold Earth][Mold Earth]],
      [[Shape Water][Shape Water]]. You use your Ki save DC for any effect that requires a saving
      throw.

    - Elemental Barrier (11th level required) ::
      As an action, you can spend 3 ki points to create a wall of elemental
      material, consisting of ten 10 feet by 10 feet panels. Each panel must be
      contiguous and are 1 foot thick. The wall obscures line of sight and lasts
      for 1 minute. The range of ranged weapon attacks that has to pass through
      the wall is halved and creatures must succeed on a Strength saving throw
      to move through the wall.

      A creature that starts their turn next to the wall or moves adjacent to it
      must make a Dexterity saving throw. On a failed saving throw, they take
      4d8 damage, or half as much on a successful one.

      Instead of an elemental wall, you can spend 5 ki points to cast
      [[Wall of Force][Wall of Force]].

    - <<Elemental Combatant>> Elemental Combatant ::
      Beginning at 3rd level, each time you make an unarmed strike or use
      elemental discipline, the damage type is your choice of: fire, cold,
      thunder, lightning, piercing, slashing, or bludgeoning damage.

      In addition, the reach of your unarmed strikes increases to 15 feet at 3rd
      level, and to 60 feet at 6th level (if you continue with it). This feature
      is deactivated whenever you are in the ethereal plane, but on your turn
      you can spend 1 ki point to activate it until the start of your next turn.

    - Elemental Defense (6th level required) ::
      Until the start of your next turn when you take the Dodge action, you can
      use your reaction to gain one of the following effects when a creature
      deals damage to you:
      + You can use a single unarmed strike against the triggering creature if
        they are within reach.
      + You can move half your speed without provoking opportunity attacks.
      + You reduce the triggering attack or spell's damage by half, unless the
        damage is psychic damage.

    - <<Elemental Shield>> Elemental Shield ::
      Starting at 3rd level, as a reaction whenever you or a friendly creature
      within 30 feet is targeted by an attack, you can create a temporary
      elemental shield to block attacks. The shield provides +2 bonus to the AC
      of the targeted creature. The shield dissipates after the attack action is
      completed. You can create only one shield at a time.

      At 3rd level, you gain the ability to levitate a nearby block of earth or
      stone to form the shield. If you continue with this discipline then you
      gain the following additional abilities at 6th, 11th, and 17th level.
      + At 6th level, you gain the ability to freeze the water in
        the environment around you to form the shield.
      + At 11th level, you gain the ability to throw up gusts of air close to
        you to form the shield.
      + At 17th level, you gain the ability to produce flames to form the
        shield.

      If you are in the ethereal plane, you can spend 1 ki point to produce the
      shield out of the ethereal equivalent of the elements.

    - Fist of Four Elements (11th level required) ::
      Whenever you deal damage with an unarmed strike, add half your monk level,
      rounded down, to the damage. You can also increase the damage of your
      unarmed strikes by spending ki points. Each point you spend, up to a
      maximum of 3, increases the damage by your monk die.

    - Leaf on the Wind (11th level required) ::
      When you use Step of the Wind, you can spend 1 ki point and gain a fly
      speed equal to your speed until the end of your next turn.

    - Primordial Shackles (6th level required) ::
      When you hit a creature with an unarmed strike, you can spend 1 ki point
      to force that creature to make a Dexterity saving throw. On a failure, the
      target is restrained for 1 minuter or until you lose your concentration
      (as if you were concentrating on a spell).

      The creature can use its action to make a Strength check against your Ki
      save DC. On a success, it frees itself.

    - Primordial Wrath (11th level required) ::
      As an action, you can produce a huge wave of elemental energy in a 30 foot
      cone. Each creature in the 30 foot cone must make a Dexterity saving throw
      or take 2d10 damage.

      You can increase the cone's damage by spending ki points. Each point you
      spend, up to maximum of 5, increases the damage by 1d10.

    - Roots of the Land (11th level required) ::
      You reach out with your ki to the ground beneath you. You gain [[Tremorsense][tremorsense]]
      with a range of 30 feet.

      Also, you can spend 2 ki points to gain a burrowing speed equal to half
      your speed until the end of your turn.

    - Shape the Flowing River (6th level required) ::
      You can spend 1 ki point to gain a swim speed equal to your normal speed
      for 1 minute. During this time, you can use your action to bring along any
      willing creature within 5 feet when you move.

    - Sweeping Elemental Strike (6th level required) ::
      When you use Flurry of Blows, you can spend an additional ki point to make
      a single unarmed strike against every creature within 5 feet of you.

    - Zephyr's Embrace (6th level required) ::
      You may use your reaction and spend 1 ki point to extend the benefits of
      Slow Fall to any creature within 30 feet of you until the start of your
      next turn.

*** Spells and abilities
- <<Control Flames>> Control Flames ::
  | Type                  | Casting Time | Range   | Duration                |
  |-----------------------+--------------+---------+-------------------------|
  | Transmutation cantrip | 1 action     | 60 feet | Instantaneous or 1 hour |

  You choose nonmagical flame that you can see within range and that fits within
  a 5-foot cube. You affect it in one of the following ways:

    - You instantaneously expand the flame 5 feet in one direction, provided
      that wood or other fuel is present in the new location.
    - You instantaneously extinguish the flames within the cube.
    - You double or halve the area of bright light and dim light cast by the
      flame, change its color, or both. The change lasts for 1 hour.
    - You cause simple shapes—such as the vague form of a creature, an inanimate
      object, or a location—to appear within the flames and animate as you
      like. The shapes last for 1 hour.

  If you cast this spell multiple times, you can have up to three
  non-instantaneous effects created by it active at a time, and you can dismiss
  such an effect as an action.

- <<Gust>> Gust ::
  | Type                  | Casting Time | Range   | Duration      |
  |-----------------------+--------------+---------+---------------|
  | Transmutation cantrip | 1 action     | 30 feet | Instantaneous |

  You seize the air and compel it to create one of the following effects at a
  point you can see within range:

    - One Medium or smaller creature that you choose must succeed on a Strength
      saving throw or be pushed up to 5 feet away from you.
    - You create a small blast of air capable of moving one object that is
      neither held nor carried and that weighs no more than 5 pounds. The object
      is pushed up to 10 feet away from you. It isn't pushed with enough force
      to cause damage.
    - You create a harmless sensory effect using air, such as causing leaves to
      rustle, wind to slam shutters closed, or your clothing to ripple in a
      breeze.

- <<Mold Earth>> Mold Earth ::
  | Type                  | Casting Time | Range   | Duration                |
  |-----------------------+--------------+---------+-------------------------|
  | Transmutation cantrip | 1 action     | 30 feet | Instantaneous or 1 hour |

  You choose a portion of dirt or stone that you can see within range and that
  fits within a 5-foot cube. You manipulate it in one of the following ways:

    - If you target an area of loose earth, you can instantaneously excavate it,
      move it along the ground, and deposit it up to 5 feet away. This movement
      doesn't involve enough force to cause damage.
    - You cause shapes, colors, or both to appear on the dirt or stone, spelling
      out words, creating images, or shaping patterns. The changes last for 1
      hour.
    - If the dirt or stone you target is on the ground, you cause it to become
      difficult terrain. Alternatively, you can cause the ground to become
      normal terrain if it is already difficult terrain. This change lasts for 1
      hour.

  If you cast this spell multiple times, you can have no more than two of its
  non-instantaneous effects active at a time, and you can dismiss such an effect
  as an action.

- <<Shape Water>> Shape Water ::
  | Type                  | Casting Time | Range   | Duration                |
  |-----------------------+--------------+---------+-------------------------|
  | Transmutation cantrip | 1 action     | 30 feet | Instantaneous or 1 hour |

  You choose an area of water that you can see within range and that fits within
  a 5-foot cube. You manipulate it in one of the following ways:

    - You instantaneously move or otherwise change the flow of the water as you
      direct, up to 5 feet in any direction. This movement doesn't have enough
      force to cause damage.
    - You cause the water to form into simple shapes and animate at your
      direction. This change lasts for 1 hour.
    - You change the water's color or opacity. The water must be changed in the
      same way throughout. This change lasts for 1 hour.
    - You freeze the water, provided that there are no creatures in it. The
      water unfreezes in 1 hour.

  If you cast this spell multiple times, you can have no more than two of its
  non-instantaneous effects active at a time, and you can dismiss such an effect
  as an action.

- <<Wall of Force>> Wall of Force ::
  | Type                | Casting Time | Range    | Duration                        |
  |---------------------+--------------+----------+---------------------------------|
  | 5th level evocation | 1 action     | 120 feet | Concentration, up to 10 minutes |

  An invisible wall of force springs into existence at a point you choose within
  range. The wall appears in any orientation you choose, as a horizontal or
  vertical barrier or at an angle. It can be free floating or resting on a solid
  surface. You can form it into a hemispherical dome or a sphere with a radius
  of up to 10 feet, or you can shape a flat surface made up of ten
  10-foot-by-10-foot panels. Each panel must be contiguous with another
  panel. In any form, the wall is 1/4 inch thick. It lasts for the duration. If
  the wall cuts through a creature's space when it appears, the creature is
  pushed to one side of the wall (your choice which side).

  Nothing can physically pass through the wall. It is immune to all damage and
  can't be dispelled by dispel magic. A disintegrate spell destroys the wall
  instantly, however. The wall also extends into the Ethereal Plane, blocking
  ethereal travel through the wall.

- <<Investiture of Flame>> Investiture of Flame ::
  | Type                    | Casting Time | Range | Duration                        |
  |-------------------------+--------------+-------+---------------------------------|
  | 6th level transmutation | 1 action     | Self  | Concentration, up to 10 minutes |

  Flames race across your body, shedding bright light in a 30-foot radius and
  dim light for an additional 30 feet for the spell's duration. The flames don't
  harm you. Until the spell ends, you gain the following benefits:

    - You are immune to fire damage and have resistance to cold damage.
    - Any creature that moves within 5 feet of you for the first time on a turn
      or ends its turn there takes 1d10 fire damage.
    - You can use your action to create a line of fire 15 feet long and 5 feet
      wide extending from you in a direction you choose. Each creature in the
      line must make a Dexterity saving throw. A creature takes 4d8 fire damage
      on a failed save, or half as much damage on a successful one.

- <<Investiture of Ice>> Investiture of Ice ::
  | Type                    | Casting Time | Range | Duration                        |
  |-------------------------+--------------+-------+---------------------------------|
  | 6th level transmutation | 1 action     | Self  | Concentration, up to 10 minutes |

  Until the spell ends, ice rimes your body, and you gain the following
  benefits:

    - You are immune to cold damage and have resistance to fire damage.
    - You can move across difficult terrain created by ice or snow without
      spending extra movement.
    - The ground in a 10-foot radius around you is icy and is difficult terrain
      for creatures other than you. The radius moves with you.
    - You can use your action to create a 15-foot cone of freezing wind
      extending from your outstretched hand in a direction you choose. Each
      creature in the cone must make a Constitution saving throw. A creature
      takes 4d6 cold damage on a failed save, or half as much damage on a
      successful one. A creature that fails its save against this effect has its
      speed halved until the start of your next turn.

- <<Investiture of Stone>> Investiture of Stone ::
  | Type                    | Casting Time | Range | Duration                        |
  |-------------------------+--------------+-------+---------------------------------|
  | 6th level transmutation | 1 action     | Self  | Concentration, up to 10 minutes |

  Until the spell ends, bits of rock spread across your body, and you gain the
  following benefits:

    - You have resistance to bludgeoning, piercing, and slashing damage from nonmagical attacks.
    - You can use your action to create a small earthquake on the ground in a
      15-foot radius centered on you. Other creatures on that ground must
      succeed on a Dexterity saving throw or be knocked prone.
    - You can move across difficult terrain made of earth or stone without
      spending extra movement. You can move through solid earth or stone as if
      it was air and without destabilizing it, but you can't end your movement
      there. If you do so, you are ejected to the nearest unoccupied space, this
      spell ends, and you are stunned until the end of your next turn.

- <<Investiture of Wind>> Investiture of Wind ::
  | Type                    | Casting Time | Range | Duration                        |
  |-------------------------+--------------+-------+---------------------------------|
  | 6th level transmutation | 1 action     | Self  | Concentration, up to 10 minutes |

  Until the spell ends, wind whirls around you, and you gain the following
  benefits:

    - Ranged weapon attacks made against you have disadvantage on the attack roll.
    - You gain a flying speed of 60 feet. If you are still flying when the spell
      ends, you fall, unless you can somehow prevent it.
    - You can use your action to create a 15-foot cube of swirling wind centered
      on a point you can see within 60 feet of you. Each creature in that area
      must make a Constitution saving throw. A creature takes 2d10 bludgeoning
      damage on a failed save, or half as much damage on a successful one. If a
      Large or smaller creature fails the save, that creature is also pushed up
      to 10 feet away from the center of the cube.

- <<Tremorsense>> Tremorsense ::
  A creature with tremorsense can detect and pinpoint the origin of vibrations
  within a specific radius, provided that the creature and the source of the
  vibrations are in contact with the same ground or substance.

  Tremorsense can't be used to detect flying or incorporeal creatures. Many
  burrowing creatures, such as ankhegs, have this special sense.

** Additional Notes

- After training under Lanner, Tansen learned to cast [[Detect Thoughts][Detect Thoughts]] by spending 2 ki points.

  + <<Detect Thoughts>> Detect Thoughts ::
    | Type                 | Casting Time | Range | Duration                      |
    |----------------------+--------------+-------+-------------------------------|
    | 2nd level divination | 1 action     | Self  | Concentration, up to 1 minute |

    For the duration, you can read the thoughts of certain creatures. When you
    cast the spell and as your action on each turn until the spell ends, you can
    focus your mind on any one creature that you can see within 30 feet of you. If
    the creature you choose has an Intelligence of 3 or lower or doesn’t speak any
    language, the creature is unaffected.

    You initially learn the surface thoughts of the creature – what is most on its
    mind in that moment. As an action, you can either shift your attention to
    another creature’s thoughts or attempt to probe deeper into the same
    creature’s mind. If you probe deeper, the target must make a Wisdom saving
    throw. If it fails, you gain insight into its reasoning (if any), its
    emotional state, and something that looms large in its mind (such as something
    it worries over, loves, or hates). If it succeeds, the spell ends. Either way,
    the target knows that you are probing into its mind, and unless you shift your
    attention to another creature’s thoughts, the creature can use its action on
    its turn to make an Intelligence check contested by your Intelligence check;
    if it succeeds, the spell ends.

    Questions verbally directed at the target creature naturally shape the course
    of its thoughts, so this spell is particularly effective as part of an
    interrogation. You can also use this spell to detect the presence of thinking
    creatures you can’t see. When you cast the spell or as your action during the
    duration, you can search for thoughts within 30 feet of you. The spell can
    penetrate barriers, but 2 feet of rock, 2 inches of any metal other than lead,
    or a thin sheet of lead blocks you. You can’t detect a creature with an
    Intelligence of 3 or lower or one that doesn’t speak any language.

    Once you detect the presence of a creature in this way, you can read its
    thoughts for the rest of the duration as described above, even if you can’t
    see it, but it must still be within range.

# * Combat * Defense

# #+NAME: Defense
# #+ATTR_HTML: :border 2 :frame border :rules all
# | Armor Class (Unarmored) | Initiative | Speed (Unarmored) |
# |-------------------------+------------+-------------------|
# |                      18 |          5 |                50 |
# #+TBLFM: @2$1=10+remote(Attributes,@3$3)+remote(Attributes,@6$3)

# - Cloak of Protection gives +1 to Armor Class.
# - +1 to Armor Class while in Barovia.
# - *Base speed:* 30.
# - Unarmored speed increases as per the [[http://engl393-dnd5th.wikia.com/wiki/Monk][Monk Leveling Table]].
# - [[http://engl393-dnd5th.wikia.com/wiki/Monk#Deflect_Missiles][Deflect Missile]]
# - [[http://dnd5e.wikia.com/wiki/Monk#Evasion][Evasion]]
# - Move across water and vertical surfaces on ground.

# ** Health

# #+NAME: Health
# #+ATTR_HTML: :border 2 :frame border :rules all
# | Hit Point Maximum | Current Hit Points | Temp Hit Points | Health Potions      |
# |-------------------+--------------------+-----------------+---------------------|
# |                97 |                 97 |                 | 11 (C), 1 (G), 1(S) |

# *** Hit Dice

# #+NAME: HD
# #+ATTR_HTML: :border 2 :frame border :rules all
# | Type | Number |
# |------+--------|
# |  1d8 |      8 |
# #+TBLFM: @2$2=remote(BASICINFO,@2$5)

# ** Weapons

# #+NAME: ImpMod
# #+ATTR_HTML: :border 2 :frame border :rules all
# | Strength Modifier | Dexterity Mod | Proficiency Bonus |
# |-------------------+---------------+-------------------|
# |                 4 |             5 |                 4 |
# #+TBLFM: @2$1=remote(Attributes,@2$3)::@2$2=remote(Attributes,@3$3)::@2$3=remote(Prof,@2$2)

# - When attacking with monk weapons or unarmed strike can use either Strength, or
#   Dexterity to attack and damage.
# - Attacking with unarmed strike or monk weapons allows unarmed strike as a bonus
#   action.
# - Ki wraps give +3 to attack and damage when attacking with monk weapons or
#   unarmed strike; +3 to save DCs.
# - Insignia of Claws gives +1 to attack and damage.
# - Can roll a d8 in place of the normal damage of unarmed strike or monk
#   weapon. This die can change with gaining of monk levels. Check martial arts
#   column of [[http://engl393-dnd5th.wikia.com/wiki/Monk][Monk Leveling Table]].
# - Proficient in monk weapons and unarmed strike.
# - Minimal armor master (feat)
#   + When you hit a creature that hasn’t taken a turn in combat yet, you deal an
#     additional 1d6 damage.
#   + When you make a standing jump, the distance you cover increases by a number
#     of feet equal to your Dexterity modifier.
#   + Any Initiative check result of yours that is lower than 8 + your Dexterity
#     modifier is raised to that
# - Trick or Treat.

# #+NAME: Weapons
# #+ATTR_HTML: :border 2 :frame border
# | Weapons             | Proficient? | Base Damage     | Type     | Range |
# |---------------------+-------------+-----------------+----------+-------|
# | Dart                | Y           | 1d4             | Piercing | 20/60 |
# | Unarmed Strike      | Y           | 1d8             | Bludgeon | 5     |
# #+TBLFM: @4$2=remote(Attributes,@3$3)
# Way of the Four Elements (homebrewed) allows an additional 1d10 + half monk level
# damage for an attack during the Attack action. The range is also increased to 60
# feet. The damage can be increased by spending ki points, up to a maximum of three.
# Each ki point spent increases the damage by 1d10.

# - 2 bottle of holy water.

# ** Ki

# #+NAME: Ki
# #+ATTR_HTML: :border 2 :frame border :rules all
# | Ki Points Maximum | Current Ki Points | Ki Save DC |
# |-------------------+-------------------+------------|
# |                12 |                12 |         15 |
# #+TBLFM: @2$1=remote(BASICINFO,@2$5)::@2$3=8+remote(Prof,@2$2)+remote(Attributes,@6$3)

# - *Ki Wraps* allow regaining up to six ki points in between two long rests.
# - *Flurry of Blows:* Immediately after attack, use 1 ki point to make two unarmed
#   strikes as a bonus action.
# - *Patient Defense:* Use 1 ki point to take the dodge action as bonus action on
#   own turn.
# - *Step of the Wind:* Use 1 ki point to disengage or dash as a bonus action on own
#   turn. Jump distance is doubled for the turn.
# - *Primordial Wrath:* As an action, you can produce a huge wave of elemental energy
#   in a 30-foot cone. Each creature in the 30-foot cone must make a Dexterity
#   saving throw or take 2d10 damage. You can increase the damage by spending ki
#   points. Each point up to a maximum of 5, increases the damage by 1d10.
# - *Detect Thoughts:* Use 2 ki points for the spell.
# - *Wall of Force:* Use 5 ki points for the spell.

# * Equipment

# - Spear
# - Dart × 10
# - Dungeoneer's Pack
#   + Backpack
#   + Crowbar
#   + Hammer
#   + Pitons × 10
#   + Torches × 10
#   + Tinderbox
#   + Ration × 10 days
#   + Waterskin
#   + Hempen rope - 50 feet
# - Uniform
# - Horn
# - Set of manacles
# - Pouch
# - +3 Ki Wraps (Requires Attunement) (C)
# - Hat of Disguise (Requires Attunement)
# - Blood Shortsword (Requires Attunement)
# - Insignia of Claws
# - Cloak of Protection (Requires Attunement) (C)
# - Periapt of Wound Closure (With Ilia)
# - Spellguard shield (AC 2) gives advantage on saving throws against spells and
#   other magical effects. Spell attacks against you have disadvantage. (With Ilia)
# - Bag of Holding
#   + Eversmoking Bowl
#   + A vial of oil of Tagg-It
# - Sending Stones
# - Dern's Instantaneous Fortress
# - Bead of Force
# - Boots of Elvenkind (Gives advantage to stealth checks that rely on moving
#   silently.)
# - Drift Globe (Cast light/daylight)
# - Ring of Warmth (C)
# - Dust of Invisibility
# - Censur of Commanding Air Elementals
#   + Air Elemental:
#     - AC - 15, HP - 90, Fly - 90ft
#     - Two slam attacks (+8 to hit, 14 bludgeoning damage eat attack),
#     - Whirlwind (DC 13, On failure 15 bludgeoning damage, flung 20ft from
#       elemental in random direction.)
# - Gem of Air Elemental
# - Potion of Invulnerability
# - Potion of Stoneskin
# - [[https://www.dnd-spells.com/spell/tensers-transformation?h=AT3felqFbI19fJ9aPx0djNer3x09L91wiMWZL3bvuxkuX3gbMdtCQ0yhwYn8co2bB10RaL3L4QeDH4XQVQ25ZIn42QkkvZwMOzkasuZW5vuCrens_imOEt4i67H-8Zj3l9Hh6B3VdHZJzfMi-Ie0][Potion of Tenser's Transformation]]
# - Scroll of Revivify (x2)
# - Scroll of Raise Dead (x2)
# - 600(300) gp worth of fancy clothes
# - 1000(500(250)) gp worth of books
# - 150 gp worth of silverware
# - Keys to Valaki burgomaster's mansion
# - Cloak of Disguise (requires attunement)

# #+NAME: Coin
# #+ATTR_HTML: :border 2 :frame border :rules all
# | PP | GP         | EP | SP     |  CP |
# |----+------------+----+--------+-----|
# |  1 | 266 (16402) | 87 | 599 () | 231 |

# * Features
# ** Dragonborn features

# - Gold Dragon. (Argenvost has narrowed down the ancestry to 6 gold dragons.)
# - Draconic Ancestry: Breathe a 15 feet cone of fire (once between rests),
#   dealing 4d6 fire damage, Dexterity save for half damage. DC  = 8 +
#   Constitution Modifier + Proficiency.
# - Resist fire damage.

# ** City Watch features

# - Have a knack for finding crime dens and constabularies.

# ** Monk features

# - Wisdom modifier added to AC when unarmoured, and not carrying a shield.
# - Can use dexterity for attack and damage when unarmed or using monk
#   weapons.
# - Can roll a d8 in place of the normal damage of unarmed strike or monk
#   weapon. This die can change with gaining of monk levels. Check martial arts
#   column of [[http://engl393-dnd5th.wikia.com/wiki/Monk][Monk Leveling Table]].
# - Can make an unarmed attack as a bonus action when unarmed or using monk
#   weapons.
# - [[http://engl393-dnd5th.wikia.com/wiki/Monk#Slow_Fall][Slow Fall]].
# - [[http://dnd5e.wikia.com/wiki/Monk#Stillness_of_Mind][Stillness of Mind]].
# - Cast [[https://www.dndbeyond.com/spells/control-flames][Control Flames]], [[https://www.dndbeyond.com/spells/gust][Gust]], [[https://www.dndbeyond.com/spells/mold-earth][Mold Earth]], and [[https://www.dndbeyond.com/spells/shape-water][Shape Water]] as cantrips. Spend 1 ki
#   point to increase their area of effect to a number of 5 foot cubes equal to
#   your monk level.

# * Taroka Cards

# - Knowledge of the ancient will help you better understand the enemy. -
#   Swashbuckler. - Skeleton of a deadly warrior lying on a bed of stone flanked
#   by gargoyles.
# - Powerful force for good and protection. Holy symbol of great hope. -
#   Mercenary - Thing you seek lies with the dead under mountains of gold coins.
# - Power and Strength. Weapon of Vengeance. A sword of sunlight. - Transmuter -
#   Go to a place of dizzying heights where the stone itself is alive.
# - Sheds light on who will help you in the battle against darkness. -
#   Broken One - Your greatest ally will be a wizard. His mind is broken but his
#   spells are strong.
# - Your enemy is a creature of darknes. Immortal. - Marionette - Look to great
#   heights. Find the beating heart of the castle. He waits nearby.

# - Great destiny - silvery staircase - Tansen.

** Monk Table

#+NAME: MONK_TABLE
| Level | Proficiency Bonus | Martial Arts | Ki Points | Unarmored Movement | Features                             |
|-------+-------------------+--------------+-----------+--------------------+--------------------------------------|
|     1 |                +2 |          1d4 |           |                    | Unarmored Defense, Martial Arts      |
|     2 |                +2 |          1d4 |         2 | +10 ft.            | Ki, Unarmored Movement               |
|     3 |                +2 |          1d4 |         3 | +10 ft.            | [[Monastic Tradition][Monastic Tradition]], Deflect Missiles |
|       |                   |              |           |                    |                                      |


* Backstory

#+INCLUDE: "./backstory.org"

# * Dark Gifts

# - Seriach (x)
# - Yrrga (x)
# - Khirad (x)
